steps:
  # Build l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/erp-btp:$SHORT_SHA', '.']
  
  # Push l'image vers Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/erp-btp:$SHORT_SHA']
  
  # Déployer sur la VM via SSH
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'saas-erp-btp-vm'
      - '--zone=europe-west9-a'
      - '--command=cd ~/erp-btp && docker-compose pull && docker-compose up -d'

images:
  - 'gcr.io/$PROJECT_ID/erp-btp:$SHORT_SHA'
